production:
  adapter: sqlite3
  database: db/production.db

development:
  adapter: sqlite3
  database: db/development.db
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.db
  timeout: 5000

