production:
  adapter: mysql
  username: root
  password: ap35h17
  database: assetmanager

development:
  adapter: sqlite3
  database: db/development.db
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.db
  timeout: 5000

